/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.diegoalba.maestredam.exam;

/**
 *
 * @author b09-05m
 */
public class BarApp extends javax.swing.JFrame {

    /**
     * Creates new form CuentasBar
     */
    public BarApp() {
        initComponents();
        setLocationRelativeTo(null);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConsumicion = new javax.swing.JLabel();
        jTextFieldConsumicion = new javax.swing.JTextField();
        jButtonMesa2 = new javax.swing.JButton();
        jButtonMesa1 = new javax.swing.JButton();
        jButtonResetMesa1 = new javax.swing.JButton();
        jButtonResetMesa2 = new javax.swing.JButton();
        jTextFieldCuentaMesa1 = new javax.swing.JTextField();
        jTextFieldCuentaMesa2 = new javax.swing.JTextField();
        jButtonSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemListaConsumiciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelConsumicion.setText("Consumicion:");

        jButtonMesa2.setText("MESA 2");
        jButtonMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa2ActionPerformed(evt);
            }
        });

        jButtonMesa1.setText("MESA 1");
        jButtonMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesa1ActionPerformed(evt);
            }
        });

        jButtonResetMesa1.setText("Reset");
        jButtonResetMesa1.setEnabled(false);
        jButtonResetMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetMesa1ActionPerformed(evt);
            }
        });

        jButtonResetMesa2.setText("Reset");
        jButtonResetMesa2.setEnabled(false);
        jButtonResetMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetMesa2ActionPerformed(evt);
            }
        });

        jTextFieldCuentaMesa1.setEditable(false);
        jTextFieldCuentaMesa1.setText("0");

        jTextFieldCuentaMesa2.setEditable(false);
        jTextFieldCuentaMesa2.setText("0");

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jMenu1.setText("Informacion");

        jMenuItemListaConsumiciones.setText("Lista Consumiciones...");
        jMenuItemListaConsumiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaConsumicionesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemListaConsumiciones);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelConsumicion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldConsumicion, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCuentaMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonResetMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonMesa2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCuentaMesa2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonResetMesa2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelConsumicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldConsumicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMesa2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jButtonMesa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonResetMesa1)
                    .addComponent(jButtonResetMesa2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCuentaMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCuentaMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButtonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa1ActionPerformed
        // TODO add your handling code here:
        consumicion = jTextFieldConsumicion.getText();
        //TRAZA
        System.out.println(consumicion);
        
        precio = 0;
        for(int i = 0;i<6;i++){
            if(consumicion.equals(nombresConsumiciones[i])){
                precio = precioConsumiciones[i];
                
                //TRAZA
                System.out.println(precio);
            }
        }
        acumulado1 = jTextFieldCuentaMesa1.getText();
        acum1 = Double.parseDouble(acumulado1);
        
        acum1 = acum1 + precio;
        cuenta1 = String.valueOf(acum1);
        jTextFieldCuentaMesa1.setText(cuenta1);
        
        jButtonResetMesa1.setEnabled(true);
    }//GEN-LAST:event_jButtonMesa1ActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonResetMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetMesa1ActionPerformed
        // TODO add your handling code here:
        jTextFieldCuentaMesa1.setText("0");
        jButtonResetMesa1.setEnabled(false);
    }//GEN-LAST:event_jButtonResetMesa1ActionPerformed

    private void jButtonResetMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetMesa2ActionPerformed
        // TODO add your handling code here:
        jTextFieldCuentaMesa2.setText("0");
        jButtonResetMesa2.setEnabled(false);
    }//GEN-LAST:event_jButtonResetMesa2ActionPerformed

    private void jButtonMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesa2ActionPerformed
        // TODO add your handling code here:
        consumicion = jTextFieldConsumicion.getText();
        //TRAZA
        System.out.println(consumicion);
        
        precio = 0;
        for(int i = 0;i<6;i++){
            if(consumicion.equals(nombresConsumiciones[i])){
                precio = precioConsumiciones[i];
                
                //TRAZA
                System.out.println(precio);
            }
        }
        acumulado2 = jTextFieldCuentaMesa2.getText();
        acum2 = Double.parseDouble(acumulado2);
        
        acum2 = acum2 + precio;
        cuenta2 = String.valueOf(acum2);
        jTextFieldCuentaMesa2.setText(cuenta2);
        
        jButtonResetMesa2.setEnabled(true);
    }//GEN-LAST:event_jButtonMesa2ActionPerformed

    private void jMenuItemListaConsumicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaConsumicionesActionPerformed
        // TODO add your handling code here:
        DlgLC.setVisible(true);
    }//GEN-LAST:event_jMenuItemListaConsumicionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMesa1;
    private javax.swing.JButton jButtonMesa2;
    private javax.swing.JButton jButtonResetMesa1;
    private javax.swing.JButton jButtonResetMesa2;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelConsumicion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemListaConsumiciones;
    private javax.swing.JTextField jTextFieldConsumicion;
    private javax.swing.JTextField jTextFieldCuentaMesa1;
    private javax.swing.JTextField jTextFieldCuentaMesa2;
    // End of variables declaration//GEN-END:variables
       
    String consumicion;
    String acumulado1;
    double acum1;
    String cuenta1;
    String acumulado2;
    double acum2;
    String cuenta2;
    
    
    double precio;
    String nombresConsumiciones[] = {"refresco","cerveza","tapa","cafe","zumo","gintonic"};
    double precioConsumiciones[] = {1.30,1.20,1,0.95,1.50,2.95};
    
    JDialogListaConsumiciones DlgLC = new JDialogListaConsumiciones(this,true);
}
